name: release

on:
  push:
    # run only against tags
    tags:
      - '*'

permissions:
  contents: write

jobs:

  goreleaser:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: false

      - name: Get dependencies, run test and static check
        run: |
          git clone --branch v0.4.3 --depth 1 https://github.com/cue-lang/cue.git
          tee -a ./cue/tools/flow/flow.go << END
          func (t *Task) AddDep(path string, dep *Task) {
            	t.addDep(path, dep)
          }
          END
          mv ./cue ../
          go mod tidy
          LATESTTAG=$(git describe --tags --abbrev=0)
          sed -i "s/v[0-9]\+\.[0-9]\+\.[0-9]\+/$LATESTTAG/" ./cmd/version.go
          make flow
          chmod +x ./cmd/flow
          zip -j flow-linux-amd64-$(git describe --tags).zip ./cmd/flow
          unzip -l flow-linux-amd64-$(git describe --tags).zip

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: flow-linux-amd64-*.zip
          draft: true