name: release

on:
  push:
    # run only against tags
    tags:
      - '*'

permissions:
  contents: write

jobs:

  goreleaser:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: false

      - name: Get dependencies, run test and static check
        run: |
          go mod tidy
          make flow
          chmod +x ./cmd/flow
          zip flow-linux-amd64.zip ./cmd/flow
          unzip -l flow-linux-amd64.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: flow-linux-amd64.zip
          draft: true