name: flow
on:
  push:
    branches:   
      - master
    paths-ignore:
      - '**.md'
      - "**.cue"
      - '**_test.go'      

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Pre
        run: |
          ls
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: false

      - name: Build
        run: |
          printenv
          go mod tidy
          make flow

      - name: Exec
        run: |
          mkdir temp1;mv ./cmd/flow ./temp1
          cd temp1
          ./flow init 
          ./flow update
          ./flow do mkdir
          test -d ./hello

