name: Test Flow
on:
  push:
    branches:   
      - master
    paths-ignore:
      - '**.md'
      - '**_test.go'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Setup actionflow
        uses: xxf098/setup-actionflow@v3
        with:
          flow-version: 'v0.7.0'
      - name: Pre
        run: |
          rm -rf cue.mod
          flow init && flow update
          flow do setup

      - name: Build
        run: |
          git clone --branch v0.4.3 --depth 1 https://github.com/cue-lang/cue.git
          tee -a ./cue/tools/flow/flow.go << END
          func (t *Task) AddDep(path string, dep *Task) {
            	t.addDep(path, dep)
          }
          END
          tee -a ./cue/tools/flow/cycle.go << ENDD
          func CheckCycle(a []*Task) errors.Error {
            return checkCycle(a)
          }
          ENDD
          mv ./cue ../
          flow do build

      - name: Test Funcs
        run: |
          flow do testFuncs 
          
      - name: Test(Reference Cycle)
        run: |
          mkdir temp1;mv ./cmd/flow ./temp1
          cd temp1
          ./flow init &&  ./flow update
          ./flow do mkdir
          test -d ./hello
          rm *.cue
          cp ../testcues/all.cue ./ && ./flow do writeAll && rm *.cue
          cp ../testcues/keep.cue ./ && ./flow do keepFile && rm *.cue
          cp ../testcues/writefile.cue ./ && ./flow do hello && rm *.cue
          cp ../testcues/exec.cue ./ && ./flow do touch && rm *.cue
          cp ../testcues/then.cue ./ && ./flow do mkdirWrite && rm *.cue
          cp ../workflow.cue ./
          ./flow do testAll
          ./flow do testKeep

