name: flow
on:
  push:
    branches:   
      - master
    paths-ignore:
      - '**.md'
      - "**.cue"
      - '**_test.go'      

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Pre
        run: |
          wget -q https://github.com/xxf098/actionflow/releases/download/v0.5.8/flow-linux-amd64-v0.5.8.zip
          unzip flow-linux-amd64-v0.5.8.zip
          rm -rf cue.mod
          ./flow init && ./flow update
          ./flow do setup

      - name: Build
        run: ./flow do build
          
      - name: Test
        run: |
          ls ./cmd
          mkdir temp1;mv ./cmd/flow ./temp1
          cd temp1
          ./flow init 
          ./flow update
          ./flow do mkdir
          test -d ./hello
          cp ../workflow.cue ./
          sed -i '1 s/^.*$/package testcues/' workflow.cue
          ./flow do testAll 
          rm *.cue
          cp ../testcues/writefile.cue ./
          ./flow do hello
          test -f hello-fileName.txt
          rm *.cue &&  cp ../testcues/writefile1.cue ./
          ./flow do hello
          test -f ./test/hello/hello-fileName.txt
          rm *.cue &&  cp ../testcues/exec.cue ./
          ./flow do touch
          test -f ./hello.txt
          rm *.cue &&  cp ../testcues/all.cue ./
          ./flow do writeAll
          test -f ./test/foo1
          test -f ./test/foo2
          rm *.cue &&  cp ../testcues/then.cue ./
          ./flow do mkdir
          test -f ./test/foo
          rm *.cue &&  cp ../testcues/mkdir_parents.cue ./
          ./flow do writeChecker
          test -f ./test/baz/foo
          rm *.cue &&  cp ../testcues/exec/output.cue ./
          ./flow do save
          test -f ./output.txt
          rm *.cue &&  cp ../testcues/exec/env.cue ./
          ./flow do verify
          rm *.cue &&  cp ../testcues/exec/workdir.cue ./
          ./flow do verify          
