name: flow
on:
  push:
    branches:   
      - master
    paths-ignore:
      - '**.md'
      - "**.cue"
      - '**_test.go'      

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Pre
        run: |
          git clone --depth=1 https://github.com/actions/setup-go.git  /home/runner/.cache/flow/actions-setup-go@v3
          env INPUT_GO-VERSION=1.19 INPUT_CHECK-LATEST=false INPUT_CACHE=true INPUT_CACHE-DEPENDENCY-PATH= RUNNER_TOOL_CACHE=/opt/hostedtoolcache RUNNER_OS=Linux RUNNER_ARCH=x64 RUNNER_TEMP=/tmp node /home/runner/.cache/flow/actions-setup-go@v3/dist/setup/index.js

      # - name: Setup Go
      #   uses: actions/setup-go@v3
      #   with:
      #     go-version: 1.18
      #     cache: false

      - name: Build
        run: |
          go version
          go mod tidy
          make flow
          ls

      - name: Test
        run: |
          mkdir temp1;mv ./cmd/flow ./temp1
          cd temp1
          ./flow init 
          ./flow update
          ./flow do mkdir
          test -d ./hello
          rm *.cue
          cp ../testcues/writefile.cue ./
          ./flow do hello
          test -f hello-fileName.txt
          rm *.cue &&  cp ../testcues/writefile1.cue ./
          ./flow do hello
          test -f ./test/hello/hello-fileName.txt
          rm *.cue &&  cp ../testcues/writefile2.cue ./
          ./flow do hello
          test -f ./test/hello-fileName.txt
   